version: "3"

services:
  postgres-rentcar:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rentcar
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api-rentcar:
    build:
      context: ./
    depends_on:
      - postgres-rentcar
    ports:
      - 8080:8080
    restart: unless-stopped