spring:
  application:
    name: Todo MVC Backend Spring
  datasource:
    generate-unique-name: true
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/todo?user=postgres&password=postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update